/*******************************************************************************
 * @file ble_server.hpp
 * @brief Contains declarations for BLE server functionality including advertising,
 * client management, service provisioning, and JSON command processing.
 *
 * @version 0.0.5
 * @date 2025-06-24
 * @author isa@sense-ai.co
 *******************************************************************************
 *******************************************************************************/

#pragma once

#include "ble_configs.hpp"

/**
 * @enum bleServerState_t
 * @brief States specific to BLE server operations
 */
typedef enum {
    BLE_SERVER_IDLE,                                ///< Server is idle
    BLE_SERVER_ADVERTISING,                         ///< Server is advertising
    BLE_SERVER_CONNECTED,                           ///< Server has clients connected
    BLE_SERVER_READY,                               ///< Server is ready for operations
    BLE_SERVER_STOPPING                             ///< Server is stopping
} bleServerState_t;

/**
 * @enum bleServerEvent_t
 * @brief Events that can be generated by the BLE server
 */
typedef enum {
    BLE_SERVER_EVENT_ADVERTISING_STARTED,           ///< Advertising started
    BLE_SERVER_EVENT_ADVERTISING_STOPPED,           ///< Advertising stopped
    BLE_SERVER_EVENT_CLIENT_CONNECTED,              ///< Client connected
    BLE_SERVER_EVENT_CLIENT_DISCONNECTED,           ///< Client disconnected
    BLE_SERVER_EVENT_CLIENT_AUTHENTICATED,          ///< Client authenticated
    BLE_SERVER_EVENT_DATA_WRITTEN,                  ///< Data written by client
    BLE_SERVER_EVENT_DATA_READ,                     ///< Data read by client
    BLE_SERVER_EVENT_JSON_COMMAND,                  ///< JSON command received
    BLE_SERVER_EVENT_ERROR                          ///< Error occurred
} bleServerEvent_t;

/**
 * @struct bleServerConfig_t
 * @brief Configuration structure for BLE server
 */
typedef struct {
    char deviceName[BLE_MAX_DEVICE_NAME_LEN];       ///< Server device name
    uint32_t advertisingInterval;                   ///< Advertising interval in milliseconds
    bool autoStartAdvertising;                      ///< Auto-start advertising on init
    uint32_t dataUpdateInterval;                    ///< Interval for automatic data updates MS
    uint8_t maxClients;                             ///< Maximum number of simultaneous clients
    uint32_t clientTimeout;                         ///< Client inactivity timeout mS
    bool requireAuthentication;                     ///< Require client authentication
    bool enableNotifications;                       ///< Enable data notifications to clients
    bool enableJsonCommands;                        ///< Enable JSON command processing
    uint32_t maxJsonSize;                           ///< Maximum JSON command size
} bleServerConfig_t;

/**
 * @struct bleClientSession_t
 * @brief Information about a connected client session
 */
typedef struct {
    uint16_t connID;                                ///< Connection ID
    esp_bd_addr_t address;                          ///< Client MAC address
    bool authenticated;                             ///< Authentication status
    uint64_t connectTime;                           ///< Connection timestamp
    uint64_t lastActivity;                          ///< Last activity timestamp
    uint32_t dataSent;                              ///< Data packets sent to this client
    uint32_t dataReceived;                          ///< Data packets received from this client
    bool notificationsEnabled;                      ///< Notifications enabled for this client
    char jsonBuffer[512];                           ///< Buffer for accumulating JSON data
    uint16_t jsonBufferPos;                         ///< Current position in JSON buffer
} bleClientSession_t;

/**
 * @struct bleServerStats_t
 * @brief Statistics for BLE server operations
 */
typedef struct {
    uint32_t advertisingCycles;                     ///< Number of advertising cycles
    uint32_t totalConnections;                      ///< Total connections received
    uint32_t currentClients;                        ///< Currently connected clients
    uint32_t successfulAuthentications;             ///< Successful authentications
    uint32_t failedAuthentications;                 ///< Failed authentication attempts
    uint32_t dataSent;                              ///< Total data packets sent
    uint32_t dataReceived;                          ///< Total data packets received
    uint32_t jsonCommandsProcessed;                 ///< JSON commands processed
    uint32_t jsonCommandsFailed;                    ///< Failed JSON commands
    uint64_t totalUpTime;                           ///< Total server uptime ms
    uint64_t startTime;                             ///< Server start timestamp
} bleServerStats_t;

/**
 * @struct bleServerStatus_t
 * @brief Current status of the BLE server
 */
typedef struct {
    bleServerState_t state;                         ///< Current server state
    uint8_t batteryLevel;                           ///< Current battery level
    char customData[BLE_MAX_CUSTOM_DATA_LEN];       ///< Current custom data
    uint8_t connectedClients;                       ///< Number of connected clients
    bool advertisingActive;                         ///< Advertising status
    uint64_t lastUpdateTime;                        ///< Last data update timestamp
    bool jsonProcessingEnabled;                     ///< JSON processing status
} bleServerStatus_t;

/**
 * @struct bleJsonCommand_t
 * @brief Structure for JSON command data
 */
typedef struct {
    uint16_t connID;                                ///< Connection ID that sent the command
    char commandJson[512];                          ///< JSON command string
    uint64_t timestamp;                             ///< Command timestamp
} bleJsonCommand_t;

/******************************************************************************/
/*                                 Callbacks                                  */
/******************************************************************************/

/**
 * @brief Callback for when a client connects to the server
 * @param connID Connection ID of the new client
 * @param client_info Information about the connected client
 */
typedef void (*bleServerClientConnectedCB_t)(uint16_t connID, 
                const bleDeviceInfo_t* client_info);

/**
 * @brief Callback for when a client disconnects from the server
 * @param connID Connection ID of the disconnected client
 * @param reason Disconnection reason
 */
typedef void (*bleServerClientDisconnectedCB_t)(uint16_t connID, int reason);

/**
 * @brief Callback for when data is written by a client
 * @param connID Connection ID of the client
 * @param data Data written by the client
 * @param length Length of the data
 */
typedef void (*bleServerDataWrittenCB_t)(uint16_t connID, const uint8_t* data, 
                                        uint16_t length);

/**
 * @brief Callback for when data is read by a client
 * @param connID Connection ID of the client
 * @param characteristic_type Type of characteristic read (battery, custom, etc.)
 */
typedef void (*bleServerDataReadCB_t)(uint16_t connID, 
                                        const char* characteristic_type);

/**
 * @brief Callback for client authentication events
 * @param connID Connection ID of the client
 * @param success True if authentication was successful
 * @param authData Authentication data provided by client
 */
typedef void (*bleServerClientAuthCB_t)(uint16_t connID, bool success, 
                                        const char* authData);

/**
 * @brief Callback for advertising events
 * @param started True if advertising started, false if stopped
 * @param errorCode Error code if operation failed
 */
typedef void (*bleServerAdvertisingCB_t)(bool started, 
                                        esp_err_t errorCode);

/**
 * @brief Callback for JSON command processing
 * @param command Pointer to the JSON command structure
 * @return True if command was processed successfully
 */
typedef bool (*bleServerJsonCommandCB_t)(const bleJsonCommand_t* command);

/******************************************************************************/
/*                                BLE Server Class                           */
/******************************************************************************/

/**
 * @brief BLE Server class for providing services to BLE clients
 * 
 * This class provides a high-level interface for BLE server operations 
 * including advertising services, managing client connections, handling 
 * authentication,serving data to connected clients, and processing JSON commands. 
 * It supports multiple simultaneous clients, automatic data updates, and 
 * comprehensive statistics tracking.
 */
class BLEServer {
public:
    /**
     * @brief Constructs a new BLEServer object with default settings
     */
    BLEServer();

    /**
     * @brief Constructs a new BLEServer object with custom configuration
     * @param config Initial configuration for the server
     */
    BLEServer(const bleServerConfig_t& config);

    /**
     * @brief Destroys the BLEServer object and cleans up resources
     */
    virtual ~BLEServer();

    /**
     * @brief Initializes the BLE server
     * 
     * Sets up the BLE server with the current configuration, creates services
     * and characteristics. Must be called before any other server operations.
     * 
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t init();

    /**
     * @brief Starts advertising the BLE services
     * 
     * Makes the server discoverable and connectable to BLE clients.
     * 
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t startAdvertising();

    /**
     * @brief Stops advertising the BLE services
     * 
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t stopAdvertising();

    /**
     * @brief Updates the battery level value
     * 
     * @param level Battery level (0-100%)
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t setBatteryLevel(uint8_t level);

    /**
     * @brief Updates the custom data value
     * 
     * @param data Custom data string to set
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t setCustomData(const char* data);

    /**
     * @brief Sends a JSON response to a specific client
     * 
     * @param connID Connection ID of the target client
     * @param jsonResponse JSON response string
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t sendJsonResponse(uint16_t connID, const char* jsonResponse);

    /**
     * @brief Sends a JSON response to all connected clients
     * 
     * @param jsonResponse JSON response string
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t sendJsonResponseToAll(const char* jsonResponse);

    /**
     * @brief Sends notifications to all connected clients
     * 
     * Notifies all clients with notifications enabled about data updates.
     * 
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t notifyAllClients();

    /**
     * @brief Sends notification to a specific client
     * 
     * @param connID Connection ID of the target client
     * @param characteristicType Type of characteristic to notify ("battery" or "custom")
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t notifyClient(uint16_t connID, const char* characteristicType);

    /**
     * @brief Disconnects a specific client
     * 
     * @param connID Connection ID of the client to disconnect
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t disconnectClient(uint16_t connID);

    /**
     * @brief Disconnects all connected clients
     * 
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t disconnectAllClients();

    /**************************************************************************/
    /*                           Configuration Methods                        */
    /**************************************************************************/

    /**
     * @brief Updates the server configuration
     * 
     * @param config New configuration to apply
     * @return esp_err_t ESP_OK on success, error code otherwise
     * @note Call init() after changing configuration
     */
    esp_err_t setConfig(const bleServerConfig_t& config);

    /**
     * @brief Gets the current server configuration
     * 
     * @return bleServerConfig_t Current configuration
     */
    bleServerConfig_t getConfig() const;

    /**
     * @brief Sets the device name for advertising
     * 
     * @param deviceName New device name
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t setDeviceName(const char* deviceName);

    /**
     * @brief Sets the advertising interval
     * 
     * @param interval Advertising interval in milliseconds
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t setAdvertisingInterval(uint32_t interval);

    /**************************************************************************/
    /*                            Callback Registration                       */
    /**************************************************************************/

    /**
     * @brief Registers callback for client connection events
     * 
     * @param callback Function to call when a client connects
     */
    void setClientConnectedCallback(bleServerClientConnectedCB_t callback);

    /**
     * @brief Registers callback for client disconnection events
     * 
     * @param callback Function to call when a client disconnects
     */
    void setClientDisconnectedCallback(bleServerClientDisconnectedCB_t callback);

    /**
     * @brief Registers callback for data write events
     * 
     * @param callback Function to call when a client writes data
     */
    void setDataWrittenCallback(bleServerDataWrittenCB_t callback);

    /**
     * @brief Registers callback for data read events
     * 
     * @param callback Function to call when a client reads data
     */
    void setDataReadCallback(bleServerDataReadCB_t callback);

    /**
     * @brief Registers callback for client authentication events
     * 
     * @param callback Function to call for authentication events
     */
    void setClientAuthCallback(bleServerClientAuthCB_t callback);

    /**
     * @brief Registers callback for advertising events
     * 
     * @param callback Function to call for advertising events
     */
    void setAdvertisingCallback(bleServerAdvertisingCB_t callback);

    /**
     * @brief Registers callback for JSON command processing
     * 
     * @param callback Function to call for JSON commands
     */
    void setJsonCommandCallback(bleServerJsonCommandCB_t callback);

    /**************************************************************************/
    /*                              Status Methods                            */
    /**************************************************************************/

    /**
     * @brief Gets the current server state
     * 
     * @return bleServerState_t Current state
     */
    bleServerState_t getState() const;

    /**
     * @brief Checks if server is currently advertising
     * 
     * @return bool True if advertising, false otherwise
     */
    bool isAdvertising() const;

    /**
     * @brief Checks if server has any connected clients
     * 
     * @return bool True if clients are connected, false otherwise
     */
    bool hasConnectedClients() const;

    /**
     * @brief Gets the number of currently connected clients
     * 
     * @return uint8_t Number of connected clients
     */
    uint8_t getConnectedClientCount() const;

    /**
     * @brief Gets current server status
     * 
     * @return bleServerStatus_t Current server status
     */
    bleServerStatus_t getStatus() const;

    /**
     * @brief Gets information about a specific client session
     * 
     * @param connID Connection ID of the client
     * @return bleClientSession_t* Pointer to client session, nullptr if not found
     */
    const bleClientSession_t* getClientSession(uint16_t connID) const;

    /**
     * @brief Gets list of all connected client sessions
     * 
     * @param sessions Output array to store client sessions
     * @param max_sessions Maximum number of sessions to return
     * @return uint8_t Number of sessions returned
     */
    uint8_t getAllClientSessions(bleClientSession_t* sessions, 
                                uint8_t max_sessions) const;

    /**
     * @brief Gets server operation statistics
     * 
     * @return bleServerStats_t Current statistics
     */
    bleServerStats_t getStats() const;

    /**
     * @brief Resets server statistics
     */
    void resetStats();

    /**************************************************************************/
    /*                              Utility Methods                           */
    /**************************************************************************/

    /**
     * @brief Gets a string representation of the current state
     * 
     * @return const char* State string
     */
    const char* kgetStateString() const;

    /**
     * @brief Gets server uptime in milliseconds
     * 
     * @return uint64_t Uptime in milliseconds
     */
    uint64_t getUptime() const;

    /**
     * @brief Performs a health check of the server
     * 
     * @return bool True if server is healthy, false otherwise
     */
    bool performHealthCheck();

    /**
     * @brief Gets memory usage information
     * 
     * @param free_heap Output parameter for free heap size
     * @param min_free_heap Output parameter for minimum free heap since boot
     */
    void getMemoryInfo(uint32_t* free_heap, uint32_t* min_free_heap) const;

    /**
     * @brief Generates a status report string
     * 
     * @param buffer Output buffer for the report
     * @param buffer_size Size of the output buffer
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t generateStatusReport(char* buffer, size_t buffer_size) const;

protected:
    /**************************************************************************/
    /*                              Internal Methods                          */
    /**************************************************************************/

    /**
     * @brief Internal GAP callback handler
     * 
     * @param event GAP event type
     * @param param Event parameters
     */
    static void gapCallback(esp_gap_ble_cb_event_t event, 
                            esp_ble_gap_cb_param_t *param);

    /**
     * @brief Internal GATTS callback handler
     * 
     * @param event GATTS event type
     * @param gatts_if GATT server interface
     * @param param Event parameters
     */
    static void gattsCallback(esp_gatts_cb_event_t event, esp_gatt_if_t gatts_if, 
                             esp_ble_gatts_cb_param_t *param);

    /**
     * @brief Validates client authentication data
     * 
     * @param connID Connection ID of the client
     * @param auth_data Authentication data to validate
     * @return bool True if authentication is valid
     */
    bool validateClientAuthentication(uint16_t connID, const char* auth_data);

    /**
     * @brief Adds a new client session
     * 
     * @param connID Connection ID of the new client
     * @param client_addr Client MAC address
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t addClientSession(uint16_t connID, const esp_bd_addr_t client_addr);

    /**
     * @brief Removes a client session
     * 
     * @param connID Connection ID of the client to remove
     * @return esp_err_t ESP_OK on success, error code otherwise
     */
    esp_err_t removeClientSession(uint16_t connID);

    /**
     * @brief Processes JSON data received from a client
     * 
     * @param connID Connection ID of the client
     * @param data JSON data received
     * @param length Length of the data
     */
    void processJsonData(uint16_t connID, const uint8_t* data, uint16_t length);

    /**
     * @brief Processes a complete JSON command
     * 
     * @param connID Connection ID of the client
     * @param json_string Complete JSON command string
     */
    void processJsonCommand(uint16_t connID, const char* json_string);

    /**
     * @brief Internal task for automatic data updates
     * 
     * @param pvParameters Task parameters
     */
    static void dataUpdateTask(void *pvParameters);

    /**
     * @brief Internal task for client timeout monitoring
     * 
     * @param pvParameters Task parameters
     */
    static void clientTimeoutTask(void *pvParameters);

private:
    /**************************************************************************/
    /*                              Member Variables                          */
    /**************************************************************************/

    bleServerConfig_t config_;                      ///< Server configuration
    bleServerState_t state_;                        ///< Current server state
    bleSecurityConfig_t securityConfig_;            ///< Security configuration
    
    esp_gatt_if_t gattsInter_;                      ///< GATT server interface
    bleServerStatus_t status_;                      ///< Current server status
    bleServerStats_t stats_;                        ///< Operation statistics
    
    // Service and characteristic handles
    uint16_t serviceHandle_;                        ///< Service handle
    uint16_t batteryCharHandle_;                    ///< Battery characteristic handle
    uint16_t customCharHandle_;                     ///< Custom characteristic handle
    uint16_t batteryDescrHandle_;                   ///< Battery descriptor handle
    uint16_t customDescrHandle_;                    ///< Custom descriptor handle
    
    // Client management
    bleClientSession_t clientSessions_[8];          ///< Array of client sessions
    uint8_t maxClients_;                            ///< Maximum number of clients
    
    // Callbacks
    bleServerClientConnectedCB_t clientConnectedCB_;        ///< Client connected callback
    bleServerClientDisconnectedCB_t clientDisconnectedCB_;  ///< Client disconnected callback
    bleServerDataWrittenCB_t dataWrittenCB_;                ///< Data written callback
    bleServerDataReadCB_t dataReadCB_;                      ///< Data read callback
    bleServerClientAuthCB_t clientAuthCB_;                  ///< Client authentication callback
    bleServerAdvertisingCB_t advertisingCB_;                ///< Advertising callback
    bleServerJsonCommandCB_t jsonCommandCB_;                ///< JSON command callback
    
    // Task handles
    TaskHandle_t dataUpdateTaskHandle_;             ///< Data update task handle
    TaskHandle_t clientTimeoutTaskHandle_;          ///< Client timeout task handle
    
    // Synchronization
    SemaphoreHandle_t clientsMutex_;                ///< Client sessions protection mutex
    SemaphoreHandle_t dataMutex_;                   ///< Data protection mutex
    
    // Data storage
    uint8_t batteryLevel_;                          ///< Current battery level
    char customData_[BLE_MAX_CUSTOM_DATA_LEN];      ///< Current custom data
    
    // Static instance for callbacks
    static BLEServer* instance_;                    ///< Static instance for C callbacks
};